(()=>{var o=document.querySelector("#gmail_input"),y=document.querySelector("#gmail_button"),h=document.querySelector("#gmail_result"),$=/^(?![.-])[A-Za-z0-9.-]+@(?![-.])[A-Za-z0-9.-]+\.[A-Za-z]{2,3}$/i;y&&(y.onclick=()=>{let e=o.value.trim().toLowerCase();e===""?(o.closest(".input").classList.remove("success"),o.closest(".input").classList.add("error"),h.innerHTML="\u041F\u043E\u043B\u0435 \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u0431\u044B\u0442\u044C \u043F\u0443\u0441\u043C"):$.test(e)?(o.closest(".input").classList.remove("error"),o.closest(".input").classList.add("success"),h.innerHTML="Email \u0432\u0430\u043B\u0438\u0434\u0435\u043D"):(o.closest(".input").classList.remove("success"),o.closest(".input").classList.add("error"),h.innerHTML="Email \u0432\u0432\u0435\u0434\u0435\u043D \u043D\u0435\u0432\u0435\u0440\u043D\u043E")});var v=document.querySelector(".parent_block"),r=document.querySelector(".child_block");if(v&&r){let p=function(){!s&&c<e?(r.style.left=`${c+=f}px`,c>=e&&(s=!0)):s&&!n&&a<t?(r.style.top=`${a+=f}px`,a>=t&&(n=!0)):n&&!d&&c>0?(r.style.left=`${c-=f}px`,c<=0&&(d=!0)):d&&!u&&a>0?(r.style.top=`${a-=f}px`,a<=0&&(u=!0)):u&&(s=!1,n=!1,d=!1,u=!1),requestAnimationFrame(p)};E=p;let e=v.offsetWidth-r.offsetWidth,t=v.offsetHeight-r.offsetHeight,c=0,a=0,s=!1,n=!1,d=!1,u=!1,f=10;p()}var E;var q=document.querySelector("#start"),b=document.querySelector("#stop"),S=document.querySelector("#reset"),L=document.querySelector("#seconds"),m=0,l=null;q&&b&&S&&L&&(q.addEventListener("click",()=>{l||(l=setInterval(()=>{m++,L.textContent=m},1e3))}),b.addEventListener("click",()=>{clearInterval(l),l=null}),S.addEventListener("click",()=>{clearInterval(l),l=null,m=0,L.textContent=m}));var _=document.querySelectorAll(".tab_content_item"),g=document.querySelectorAll(".tab_content_block");_.length&&g.length&&(g[0].classList.add("active"),_.forEach((e,t)=>{t===0&&e.classList.add("tab_content_item_active"),e.onclick=c=>{let a=e.getAttribute("data-name");_.forEach(s=>s.classList.remove("tab_content_item_active")),e.classList.add("tab_content_item_active"),g.forEach(s=>{s.getAttribute("data-name")===a?s.classList.add("active"):s.classList.remove("active")})}}));fetch("js/characters.json").then(e=>e.json()).then(e=>{e.forEach(t=>{document.querySelector(".characters-list").innerHTML+=`
          <div class="character-card">
            <div class="character-photo">
              <img src="${t.person_photo}" alt="${t.name}">
            </div>
            <h3 class="character-name">${t.name}, <br> \u0432\u043E\u0437\u0440\u0430\u0441\u0442: ${t.age}</h3>
            <p class="character-desc">${t.short_desc}</p>

          </div>
        `})}).catch(e=>console.error("\u041E\u0448\u0438\u0431\u043A\u0430:",e));var i=new XMLHttpRequest;i.open("GET","js/bio.json");i.setRequestHeader("Content-Type","application/json");i.send();i.onload=()=>{let e=JSON.parse(i.responseText);console.log(`${e.name} ${e.age} \u043B\u0435\u0442 ${e.status}`)};})();
